markdown: kramdown
highlighter: rouge
permalink: /:categories/:title 

github: zmj1316
author: "Key Zhang"
email: zmj1316#gmail.com
name: "zmj1316's Blog"
baseurl: /
url: https://zmj1316.github.io
domain: zmj1316.github.io

all_categories: [
  ["tag", "标签","/tags"],
  ["category", "分类","/category"],
  ["about", "关于","/about"]
]

url_categories: [
  ["other", "其他","/category#other"]
]

paginate: 10 
paginate_path: "index_:num"

index_layout: "index.html"
category_layout: "_layouts/category.html"
tag_layout: "_layouts/tag.html"
excerpt_separator:  '<!--more-->'

#不使用gems库中的jekyll-paginate-category
#使用基于jekyll-paginate改写的的栏目分页插件，所以jekyll-paginate还需要用上。
#gems: [jekyll-paginate,jekyll-paginate-category]
gems: [jekyll-paginate,jekyll-sitemap]

collections:
  docs:
    output: true

copyright: []
timezone: Asia/Shanghai

theme: jekyll-theme-leap-day
safe: false